### ISSUE TITLE
What does the "Run if logged in" setting do?

### ISSUE THREAD

**Issue by Fitzsimmons** [Lartsch/FediAct#24]
Can you please explain the purpose of the "Run if logged in" setting in the documentation somewhere?

**Comment by Lartsch** [comment]
Hi, I renamed the setting for the next version to "Ignore sessions"

It means that if enabled and you browse an instance, where you are logged in but which is not your home instance, FediAct would still run. Most users do not want to enable this, since they prefer to use their actual account on such instances.
